import RiemannHypothesis.AdelicFlow.G4TransverseGeometry
import Mathlib.NumberTheory.Padics.LocalField
import Mathlib.NumberTheory.Padics.RingHoms
import Mathlib.MeasureTheory.Measure.Haar.Basic
import Mathlib.MeasureTheory.Group.Measure

noncomputable section

open Set
open scoped ENNReal

namespace RiemannHypothesis.AdelicFlow

/-!
# G4: the measure-theoretic transverse Jacobian

The algebraic G4 files identify the stable transverse return at a prime `p`
with multiplication by `p^m` in the distinguished `p`-adic direction.  This
file upgrades that modulus to a genuine additive-Haar measure statement.

There are two conventions which must be kept separate:

* **image-set Jacobian**: `μ(p^m S) = p^{-m} μ(S)`;
* **pushforward measure**: for the invertible map on `ℚ_p`,
  `(x ↦ p^m x)_* μ = p^m μ`, because pushforward evaluates inverse images.

The G4 half-density uses the first convention.
-/

namespace G4Haar

/-- Additive Haar probability measure on the compact group of `p`-adic integers.
It is normalized by the whole compact group, so `μ(ℤ_p)=1`. -/
noncomputable def padicIntegerHaar (p : ℕ) [Fact p.Prime] : MeasureTheory.Measure ℤ_[p] :=
  MeasureTheory.Measure.addHaarMeasure ⊤

deriving MeasureTheory.Measure.IsAddHaarMeasure

@[simp]
theorem padicIntegerHaar_univ (p : ℕ) [Fact p.Prime] :
    padicIntegerHaar p (Set.univ : Set ℤ_[p]) = 1 := by
  exact MeasureTheory.Measure.addHaarMeasure_self

/-- The compact-open stable lattice `p^m ℤ_p`, expressed as the principal
ideal generated by `p^m`. -/
def padicStableLattice (p m : ℕ) [Fact p.Prime] : AddSubgroup ℤ_[p] :=
  (Ideal.span {(p : ℤ_[p]) ^ m}).toAddSubgroup

/-- Reduction modulo `p^m` is surjective. -/
theorem toZModPow_surjective (p m : ℕ) [Fact p.Prime] :
    Function.Surjective (PadicInt.toZModPow (p := p) m) := by
  intro z
  refine ⟨(z.val : ℤ_[p]), ?_⟩
  simpa using (map_natCast (PadicInt.toZModPow (p := p) m) z.val)

/-- The stable lattice is the additive kernel of reduction modulo `p^m`. -/
theorem padicStableLattice_eq_ker (p m : ℕ) [Fact p.Prime] :
    padicStableLattice p m = (PadicInt.toZModPow (p := p) m).toAddMonoidHom.ker := by
  ext x
  change x ∈ (Ideal.span {(p : ℤ_[p]) ^ m} : Ideal ℤ_[p]) ↔
    PadicInt.toZModPow (p := p) m x = 0
  rw [← RingHom.mem_ker, PadicInt.ker_toZModPow]

/-- The additive index of `p^m ℤ_p` in `ℤ_p` is exactly `p^m`. -/
theorem padicStableLattice_index (p m : ℕ) [Fact p.Prime] :
    (padicStableLattice p m).index = p ^ m := by
  let f : ℤ_[p] →+ ZMod (p ^ m) :=
    (PadicInt.toZModPow (p := p) m).toAddMonoidHom
  have hf : Function.Surjective f := toZModPow_surjective p m
  have hidx :=
    (⊥ : AddSubgroup (ZMod (p ^ m))).index_comap_of_surjective hf
  have hker : (⊥ : AddSubgroup (ZMod (p ^ m))).comap f = padicStableLattice p m := by
    rw [padicStableLattice_eq_ker]
    rfl
  rw [hker] at hidx
  simpa using hidx

/-- The stable lattice is a closed, hence measurable, compact-open subgroup. -/
theorem padicStableLattice_measurable (p m : ℕ) [Fact p.Prime] :
    MeasurableSet (padicStableLattice p m : Set ℤ_[p]) := by
  have hset :
      (padicStableLattice p m : Set ℤ_[p]) =
        {x : ℤ_[p] | ‖x‖ ≤ (p : ℝ) ^ (-(m : ℤ))} := by
    ext x
    change x ∈ (Ideal.span {(p : ℤ_[p]) ^ m} : Ideal ℤ_[p]) ↔
      ‖x‖ ≤ (p : ℝ) ^ (-(m : ℤ))
    exact (PadicInt.norm_le_pow_iff_mem_span_pow x m).symm
  rw [hset]
  exact (isClosed_le continuous_norm continuous_const).measurableSet

/-- The normalized additive Haar mass of the stable lattice is exactly
`(p^m)^{-1}`.  This is the genuine measure-theoretic source of the G4
transverse Jacobian. -/
theorem padicStableLattice_measure (p m : ℕ) [Fact p.Prime] :
    padicIntegerHaar p (padicStableLattice p m : Set ℤ_[p]) =
      ((p ^ m : ℕ) : ℝ≥0∞)⁻¹ := by
  letI : (padicStableLattice p m).FiniteIndex :=
    ⟨by
      rw [padicStableLattice_index]
      exact pow_ne_zero _ (Fact.out : Nat.Prime p).ne_zero⟩
  have h := AddSubgroup.index_mul_measure
    (padicStableLattice p m)
    (padicStableLattice_measurable p m)
    (padicIntegerHaar p)
  have hmul :
      padicIntegerHaar p (padicStableLattice p m : Set ℤ_[p]) *
          ((p ^ m : ℕ) : ℝ≥0∞) = 1 := by
    rw [padicStableLattice_index] at h
    simpa [padicIntegerHaar_univ, mul_comm] using h
  exact ENNReal.eq_inv_of_mul_eq_one_left hmul

/-- The local stable return map on the canonical compact-open `p`-adic chart. -/
def stablePadicReturn (p m : ℕ) [Fact p.Prime] (x : ℤ_[p]) : ℤ_[p] :=
  (p : ℤ_[p]) ^ m * x

/-- The image of the stable local return is exactly `p^m ℤ_p`. -/
theorem range_stablePadicReturn (p m : ℕ) [Fact p.Prime] :
    Set.range (stablePadicReturn p m) = (padicStableLattice p m : Set ℤ_[p]) := by
  ext y
  simp [stablePadicReturn, padicStableLattice, Ideal.mem_span_singleton,
    dvd_def, eq_comm]

/-- Measure-theoretic image Jacobian of the stable prime return on the canonical
compact-open chart: the image of the unit lattice under multiplication by
`p^m` has mass `p^{-m}`. -/
theorem stable_padic_image_jacobian (p m : ℕ) [Fact p.Prime] :
    padicIntegerHaar p (stablePadicReturn p m '' (Set.univ : Set ℤ_[p])) =
      ((p ^ m : ℕ) : ℝ≥0∞)⁻¹ := by
  rw [Set.image_univ, range_stablePadicReturn]
  exact padicStableLattice_measure p m

/-- Ratio form of the image-set Jacobian. -/
theorem stable_padic_image_jacobian_ratio (p m : ℕ) [Fact p.Prime] :
    padicIntegerHaar p (stablePadicReturn p m '' (Set.univ : Set ℤ_[p])) =
      ((p ^ m : ℕ) : ℝ≥0∞)⁻¹ *
        padicIntegerHaar p (Set.univ : Set ℤ_[p]) := by
  rw [stable_padic_image_jacobian, padicIntegerHaar_univ, mul_one]

end G4Haar

end RiemannHypothesis.AdelicFlow
