import RiemannHypothesis.AdelicFlow.GlobalSpace

noncomputable section

namespace RiemannHypothesis.AdelicFlow

/-!
# G2: quotient by principal rational scaling

We form the orbit relation on the rational adele carrier generated by the
canonical action of `ℚˣ` from `GlobalSpace.lean`.

Two points are equivalent exactly when one is obtained from the other by one
principal rational scaling.  Because `ℚˣ` is a group and `globalScale` is a
group action, this is already an equivalence relation.

Important: quotienting by the same `ℚˣ` action makes principal rational scaling
trivial on the quotient.  Therefore the future nontrivial logarithmic flow must
come from an external scaling action which preserves principal orbits (for
example a larger adelic/idèlic scaling action), not from `ℚˣ` itself.
-/

/-- Principal-rational orbit equivalence on the global rational adele carrier. -/
def PrincipalEquivalent (a b : GlobalSpace) : Prop :=
  ∃ u : ℚˣ, globalScale u a = b

/-- Reflexivity follows from scaling by `1`. -/
theorem principalEquivalent_refl (a : GlobalSpace) : PrincipalEquivalent a a := by
  refine ⟨1, ?_⟩
  exact globalScale_one a

/-- Symmetry follows by scaling with the inverse rational unit. -/
theorem principalEquivalent_symm {a b : GlobalSpace}
    (h : PrincipalEquivalent a b) : PrincipalEquivalent b a := by
  rcases h with ⟨u, rfl⟩
  refine ⟨u⁻¹, ?_⟩
  rw [← globalScale_mul]
  simp

/-- Transitivity is multiplication of the two principal rational scales. -/
theorem principalEquivalent_trans {a b c : GlobalSpace}
    (hab : PrincipalEquivalent a b) (hbc : PrincipalEquivalent b c) :
    PrincipalEquivalent a c := by
  rcases hab with ⟨u, hu⟩
  rcases hbc with ⟨v, hv⟩
  refine ⟨v * u, ?_⟩
  rw [globalScale_mul, hu, hv]

/-- The principal scaling relation is a genuine setoid. -/
def principalSetoid : Setoid GlobalSpace where
  r := PrincipalEquivalent
  iseqv := ⟨principalEquivalent_refl, principalEquivalent_symm,
    principalEquivalent_trans⟩

/-- The set-level principal quotient `𝔸_ℚ / ℚˣ` used at G2.

This is an orbit-set quotient.  Topological/groupoid/noncommutative refinements
are deliberately deferred to later stages. -/
abbrev PrincipalQuotient : Type := Quotient principalSetoid

/-- Canonical map from the pre-quotient adelic carrier to its principal orbit
quotient. -/
def toPrincipalQuotient (a : GlobalSpace) : PrincipalQuotient :=
  Quotient.mk principalSetoid a

/-- Scaling a representative by a principal rational unit does not change its
quotient class. -/
theorem quotient_eq_of_principal_scale (u : ℚˣ) (a : GlobalSpace) :
    toPrincipalQuotient a = toPrincipalQuotient (globalScale u a) := by
  apply Quotient.sound
  exact ⟨u, rfl⟩

/-- Equivalently, every principal rational scaling acts trivially after taking
the quotient. -/
theorem principal_scale_trivial_on_quotient (u : ℚˣ) (a : GlobalSpace) :
    toPrincipalQuotient (globalScale u a) = toPrincipalQuotient a := by
  exact (quotient_eq_of_principal_scale u a).symm

/-- Equality of principal quotient classes follows from principal equivalence. -/
theorem quotient_eq_of_principalEquivalent {a b : GlobalSpace}
    (h : PrincipalEquivalent a b) :
    toPrincipalQuotient a = toPrincipalQuotient b := by
  exact Quotient.sound h

/-! ## Descent criterion for the future logarithmic flow -/

/-- A map on the pre-quotient space respects principal rational orbits. -/
def RespectsPrincipalOrbits (F : GlobalSpace → GlobalSpace) : Prop :=
  ∀ ⦃a b : GlobalSpace⦄,
    PrincipalEquivalent a b → PrincipalEquivalent (F a) (F b)

/-- A convenient sufficient condition: a map commutes with every principal
rational scaling. -/
def CommutesWithPrincipalScaling (F : GlobalSpace → GlobalSpace) : Prop :=
  ∀ (u : ℚˣ) (a : GlobalSpace),
    F (globalScale u a) = globalScale u (F a)

/-- Any map commuting with principal scaling preserves principal orbit classes. -/
theorem respectsPrincipalOrbits_of_commutes
    {F : GlobalSpace → GlobalSpace}
    (hF : CommutesWithPrincipalScaling F) :
    RespectsPrincipalOrbits F := by
  intro a b hab
  rcases hab with ⟨u, hu⟩
  refine ⟨u, ?_⟩
  rw [← hF u a, hu]

/-- Any principal-orbit-compatible map descends canonically to the quotient. -/
def descendToPrincipalQuotient (F : GlobalSpace → GlobalSpace)
    (hF : RespectsPrincipalOrbits F) :
    PrincipalQuotient → PrincipalQuotient :=
  Quotient.lift
    (fun a => toPrincipalQuotient (F a))
    (by
      intro a b hab
      exact Quotient.sound (hF hab))

@[simp]
theorem descendToPrincipalQuotient_mk
    (F : GlobalSpace → GlobalSpace)
    (hF : RespectsPrincipalOrbits F)
    (a : GlobalSpace) :
    descendToPrincipalQuotient F hF (toPrincipalQuotient a) =
      toPrincipalQuotient (F a) := rfl

/-- Strong G2 descent theorem: commuting with principal rational scaling is
sufficient for a global map to induce a well-defined map on `𝔸_ℚ / ℚˣ`. -/
def descendCommutingMap (F : GlobalSpace → GlobalSpace)
    (hF : CommutesWithPrincipalScaling F) :
    PrincipalQuotient → PrincipalQuotient :=
  descendToPrincipalQuotient F (respectsPrincipalOrbits_of_commutes hF)

@[simp]
theorem descendCommutingMap_mk
    (F : GlobalSpace → GlobalSpace)
    (hF : CommutesWithPrincipalScaling F)
    (a : GlobalSpace) :
    descendCommutingMap F hF (toPrincipalQuotient a) =
      toPrincipalQuotient (F a) := rfl

/-! ## The next dynamical boundary

A genuine continuous logarithmic flow must satisfy the group law on `ℝ` and
commute with all principal rational scalings.  Those two properties are enough
to descend it to the principal quotient.
-/

/-- Exact G2 boundary for a future continuous logarithmic flow. -/
structure QuotientFlowBoundary where
  flow : ℝ → GlobalSpace → GlobalSpace
  zero : ∀ a, flow 0 a = a
  add : ∀ s t a, flow (s + t) a = flow s (flow t a)
  principal_commutation : ∀ t, CommutesWithPrincipalScaling (flow t)

/-- Every flow satisfying the G2 boundary descends pointwise to the principal
quotient. -/
def QuotientFlowBoundary.quotientFlow
    (B : QuotientFlowBoundary) (t : ℝ) :
    PrincipalQuotient → PrincipalQuotient :=
  descendCommutingMap (B.flow t) (B.principal_commutation t)

@[simp]
theorem QuotientFlowBoundary.quotientFlow_mk
    (B : QuotientFlowBoundary) (t : ℝ) (a : GlobalSpace) :
    B.quotientFlow t (toPrincipalQuotient a) =
      toPrincipalQuotient (B.flow t a) := rfl

/-- The descended flow inherits the zero-time identity. -/
theorem QuotientFlowBoundary.quotientFlow_zero
    (B : QuotientFlowBoundary) (x : PrincipalQuotient) :
    B.quotientFlow 0 x = x := by
  refine Quotient.inductionOn x ?_
  intro a
  simp [QuotientFlowBoundary.quotientFlow, B.zero]

/-- The descended flow inherits the additive flow law. -/
theorem QuotientFlowBoundary.quotientFlow_add
    (B : QuotientFlowBoundary) (s t : ℝ) (x : PrincipalQuotient) :
    B.quotientFlow (s + t) x = B.quotientFlow s (B.quotientFlow t x) := by
  refine Quotient.inductionOn x ?_
  intro a
  simp [QuotientFlowBoundary.quotientFlow, B.add]

/-- G2 summary: the principal quotient exists, principal rational scaling is
identified exactly, and any future continuous flow commuting with that scaling
descends with its flow law intact. -/
theorem G2_principal_quotient_and_descent :
    (∀ u : ℚˣ, ∀ a : GlobalSpace,
      toPrincipalQuotient (globalScale u a) = toPrincipalQuotient a) ∧
    (∀ B : QuotientFlowBoundary, ∀ s t : ℝ, ∀ x : PrincipalQuotient,
      B.quotientFlow (s + t) x = B.quotientFlow s (B.quotientFlow t x)) := by
  constructor
  · exact principal_scale_trivial_on_quotient
  · intro B s t x
    exact B.quotientFlow_add s t x

end RiemannHypothesis.AdelicFlow
