import RiemannHypothesis.AdelicFlow.GlobalSpace

noncomputable section

namespace RiemannHypothesis.AdelicFlow

/-!
# G2: quotient by principal rational scaling

We form the orbit relation on the rational adele carrier generated by the
canonical action of `ℚˣ` from `GlobalSpace.lean`.

Important: quotienting by the same `ℚˣ` action makes principal rational scaling
trivial on the quotient.  Therefore the future nontrivial logarithmic flow must
come from an external scaling action preserving principal orbits.
-/

def PrincipalEquivalent (a b : GlobalSpace) : Prop :=
  ∃ u : ℚˣ, globalScale u a = b

theorem principalEquivalent_refl (a : GlobalSpace) : PrincipalEquivalent a a := by
  exact ⟨1, globalScale_one a⟩

theorem principalEquivalent_symm {a b : GlobalSpace}
    (h : PrincipalEquivalent a b) : PrincipalEquivalent b a := by
  rcases h with ⟨u, rfl⟩
  refine ⟨u⁻¹, ?_⟩
  rw [← globalScale_mul]
  simp

theorem principalEquivalent_trans {a b c : GlobalSpace}
    (hab : PrincipalEquivalent a b) (hbc : PrincipalEquivalent b c) :
    PrincipalEquivalent a c := by
  rcases hab with ⟨u, hu⟩
  rcases hbc with ⟨v, hv⟩
  refine ⟨v * u, ?_⟩
  rw [globalScale_mul, hu, hv]

def principalSetoid : Setoid GlobalSpace where
  r := PrincipalEquivalent
  iseqv := ⟨principalEquivalent_refl, principalEquivalent_symm,
    principalEquivalent_trans⟩

abbrev PrincipalQuotient : Type := Quotient principalSetoid

def toPrincipalQuotient (a : GlobalSpace) : PrincipalQuotient :=
  Quotient.mk principalSetoid a

theorem quotient_eq_of_principal_scale (u : ℚˣ) (a : GlobalSpace) :
    toPrincipalQuotient a = toPrincipalQuotient (globalScale u a) := by
  apply Quotient.sound
  exact ⟨u, rfl⟩

theorem principal_scale_trivial_on_quotient (u : ℚˣ) (a : GlobalSpace) :
    toPrincipalQuotient (globalScale u a) = toPrincipalQuotient a := by
  exact (quotient_eq_of_principal_scale u a).symm

theorem quotient_eq_of_principalEquivalent {a b : GlobalSpace}
    (h : PrincipalEquivalent a b) :
    toPrincipalQuotient a = toPrincipalQuotient b := by
  exact Quotient.sound h

/-! ## Descent criterion for the logarithmic flow -/

def RespectsPrincipalOrbits (F : GlobalSpace → GlobalSpace) : Prop :=
  ∀ ⦃a b : GlobalSpace⦄,
    PrincipalEquivalent a b → PrincipalEquivalent (F a) (F b)

def CommutesWithPrincipalScaling (F : GlobalSpace → GlobalSpace) : Prop :=
  ∀ (u : ℚˣ) (a : GlobalSpace),
    F (globalScale u a) = globalScale u (F a)

theorem respectsPrincipalOrbits_of_commutes
    {F : GlobalSpace → GlobalSpace}
    (hF : CommutesWithPrincipalScaling F) :
    RespectsPrincipalOrbits F := by
  intro a b hab
  rcases hab with ⟨u, hu⟩
  refine ⟨u, ?_⟩
  rw [← hF u a, hu]

def descendToPrincipalQuotient (F : GlobalSpace → GlobalSpace)
    (hF : RespectsPrincipalOrbits F) :
    PrincipalQuotient → PrincipalQuotient :=
  Quotient.lift
    (fun a => toPrincipalQuotient (F a))
    (by
      intro a b hab
      exact Quotient.sound (hF hab))

@[simp]
theorem descendToPrincipalQuotient_mk
    (F : GlobalSpace → GlobalSpace)
    (hF : RespectsPrincipalOrbits F)
    (a : GlobalSpace) :
    descendToPrincipalQuotient F hF (toPrincipalQuotient a) =
      toPrincipalQuotient (F a) := rfl

def descendCommutingMap (F : GlobalSpace → GlobalSpace)
    (hF : CommutesWithPrincipalScaling F) :
    PrincipalQuotient → PrincipalQuotient :=
  descendToPrincipalQuotient F (respectsPrincipalOrbits_of_commutes hF)

@[simp]
theorem descendCommutingMap_mk
    (F : GlobalSpace → GlobalSpace)
    (hF : CommutesWithPrincipalScaling F)
    (a : GlobalSpace) :
    descendCommutingMap F hF (toPrincipalQuotient a) =
      toPrincipalQuotient (F a) := rfl

/-! ## The next dynamical boundary -/

structure QuotientFlowBoundary where
  flow : ℝ → GlobalSpace → GlobalSpace
  zero : ∀ a, flow 0 a = a
  add : ∀ s t a, flow (s + t) a = flow s (flow t a)
  principal_commutation : ∀ t, CommutesWithPrincipalScaling (flow t)

def QuotientFlowBoundary.quotientFlow
    (B : QuotientFlowBoundary) (t : ℝ) :
    PrincipalQuotient → PrincipalQuotient :=
  descendCommutingMap (B.flow t) (B.principal_commutation t)

@[simp]
theorem QuotientFlowBoundary.quotientFlow_mk
    (B : QuotientFlowBoundary) (t : ℝ) (a : GlobalSpace) :
    B.quotientFlow t (toPrincipalQuotient a) =
      toPrincipalQuotient (B.flow t a) := rfl

theorem QuotientFlowBoundary.quotientFlow_zero
    (B : QuotientFlowBoundary) (x : PrincipalQuotient) :
    B.quotientFlow 0 x = x := by
  refine Quotient.inductionOn x ?_
  intro a
  change toPrincipalQuotient (B.flow 0 a) = toPrincipalQuotient a
  rw [B.zero]

theorem QuotientFlowBoundary.quotientFlow_add
    (B : QuotientFlowBoundary) (s t : ℝ) (x : PrincipalQuotient) :
    B.quotientFlow (s + t) x = B.quotientFlow s (B.quotientFlow t x) := by
  refine Quotient.inductionOn x ?_
  intro a
  change toPrincipalQuotient (B.flow (s + t) a) =
    toPrincipalQuotient (B.flow s (B.flow t a))
  rw [B.add]

theorem G2_principal_quotient_and_descent :
    (∀ u : ℚˣ, ∀ a : GlobalSpace,
      toPrincipalQuotient (globalScale u a) = toPrincipalQuotient a) ∧
    (∀ B : QuotientFlowBoundary, ∀ s t : ℝ, ∀ x : PrincipalQuotient,
      B.quotientFlow (s + t) x = B.quotientFlow s (B.quotientFlow t x)) := by
  constructor
  · exact principal_scale_trivial_on_quotient
  · intro B s t x
    exact B.quotientFlow_add s t x

end RiemannHypothesis.AdelicFlow
